/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSignInRouteImport } from './routes/onboarding_.sign-in'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppShellRouteImport } from './routes/_app._shell'
import { Route as WorkspacesWorkspaceIdVscodeRouteImport } from './routes/workspaces.$workspaceId.vscode'
import { Route as AppWorkspacesElectricTestRouteImport } from './routes/_app.workspaces_.electric-test'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppShellWorkspacesRouteImport } from './routes/_app._shell.workspaces'
import { Route as AppShellRoutinesRouteImport } from './routes/_app._shell.routines'
import { Route as AppHostsHostIdWorkspacesRouteImport } from './routes/_app.hosts.$hostId.workspaces'
import { Route as AppShellWorkspacesWorkspaceIdRouteImport } from './routes/_app._shell.workspaces_.$workspaceId'
import { Route as AppShellRoutinesNewRouteImport } from './routes/_app._shell.routines_.new'
import { Route as AppShellRoutinesRoutineIdRouteImport } from './routes/_app._shell.routines_.$routineId'
import { Route as HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport } from './routes/hosts.$hostId.workspaces.$workspaceId.vscode'
import { Route as AppProjectsProjectIdIssuesIssueIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId'
import { Route as AppHostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.hosts.$hostId.workspaces_.$workspaceId'
import { Route as AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.workspaces.$workspaceId'
import { Route as AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.hosts.$hostId.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.hosts.$hostId.workspaces.$workspaceId'
import { Route as AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.hosts.$hostId.workspaces.create.$draftId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSignInRoute = OnboardingSignInRouteImport.update({
  id: '/onboarding_/sign-in',
  path: '/onboarding/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppShellRoute = AppShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AppRoute,
} as any)
const WorkspacesWorkspaceIdVscodeRoute =
  WorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/workspaces/$workspaceId/vscode',
    path: '/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesElectricTestRoute =
  AppWorkspacesElectricTestRouteImport.update({
    id: '/workspaces_/electric-test',
    path: '/workspaces/electric-test',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppShellWorkspacesRoute = AppShellWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellRoutinesRoute = AppShellRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppShellRoute,
} as any)
const AppHostsHostIdWorkspacesRoute =
  AppHostsHostIdWorkspacesRouteImport.update({
    id: '/hosts/$hostId/workspaces',
    path: '/hosts/$hostId/workspaces',
    getParentRoute: () => AppRoute,
  } as any)
const AppShellWorkspacesWorkspaceIdRoute =
  AppShellWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces_/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppShellRoute,
  } as any)
const AppShellRoutinesNewRoute = AppShellRoutinesNewRouteImport.update({
  id: '/routines_/new',
  path: '/routines/new',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellRoutinesRoutineIdRoute =
  AppShellRoutinesRoutineIdRouteImport.update({
    id: '/routines_/$routineId',
    path: '/routines/$routineId',
    getParentRoute: () => AppShellRoute,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdVscodeRoute =
  HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    path: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProjectsProjectIdIssuesIssueIdRoute =
  AppProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId',
    path: '/projects/$projectId/issues/$issueId',
    getParentRoute: () => AppRoute,
  } as any)
const AppHostsHostIdWorkspacesWorkspaceIdRoute =
  AppHostsHostIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/hosts/$hostId/workspaces_/$workspaceId',
    path: '/hosts/$hostId/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/projects/$projectId_/workspaces/create/$draftId',
    path: '/projects/$projectId/workspaces/create/$draftId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute =
  AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId',
    path: '/projects/$projectId/issues/$issueId/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId',
    path: '/projects/$projectId/issues/$issueId/workspaces/create/$draftId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId',
    path: '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute =
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRouteImport.update(
    {
      id: '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId',
      path: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId',
      getParentRoute: () => AppRoute,
    } as any,
  )
const AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRouteImport.update(
    {
      id: '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId',
      path: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId',
      getParentRoute: () => AppRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/export': typeof AppExportRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/routines': typeof AppShellRoutinesRoute
  '/workspaces': typeof AppShellWorkspacesRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspaces/electric-test': typeof AppWorkspacesElectricTestRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/routines/$routineId': typeof AppShellRoutinesRoutineIdRoute
  '/routines/new': typeof AppShellRoutinesNewRoute
  '/workspaces/$workspaceId': typeof AppShellWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/export': typeof AppExportRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/routines': typeof AppShellRoutinesRoute
  '/workspaces': typeof AppShellWorkspacesRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspaces/electric-test': typeof AppWorkspacesElectricTestRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/routines/$routineId': typeof AppShellRoutinesRoutineIdRoute
  '/routines/new': typeof AppShellRoutinesNewRoute
  '/workspaces/$workspaceId': typeof AppShellWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/_shell': typeof AppShellRouteWithChildren
  '/_app/export': typeof AppExportRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/onboarding_/sign-in': typeof OnboardingSignInRoute
  '/_app/_shell/routines': typeof AppShellRoutinesRoute
  '/_app/_shell/workspaces': typeof AppShellWorkspacesRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/workspaces_/electric-test': typeof AppWorkspacesElectricTestRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/_app/_shell/routines_/$routineId': typeof AppShellRoutinesRoutineIdRoute
  '/_app/_shell/routines_/new': typeof AppShellRoutinesNewRoute
  '/_app/_shell/workspaces_/$workspaceId': typeof AppShellWorkspacesWorkspaceIdRoute
  '/_app/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/_app/hosts/$hostId/workspaces_/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/_app/projects/$projectId_/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/_app/projects/$projectId_/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/export'
    | '/notifications'
    | '/onboarding/sign-in'
    | '/routines'
    | '/workspaces'
    | '/projects/$projectId'
    | '/workspaces/electric-test'
    | '/workspaces/$workspaceId/vscode'
    | '/routines/$routineId'
    | '/routines/new'
    | '/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
    | '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/export'
    | '/notifications'
    | '/onboarding/sign-in'
    | '/routines'
    | '/workspaces'
    | '/projects/$projectId'
    | '/workspaces/electric-test'
    | '/workspaces/$workspaceId/vscode'
    | '/routines/$routineId'
    | '/routines/new'
    | '/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
    | '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/_shell'
    | '/_app/export'
    | '/_app/notifications'
    | '/onboarding_/sign-in'
    | '/_app/_shell/routines'
    | '/_app/_shell/workspaces'
    | '/_app/projects/$projectId'
    | '/_app/workspaces_/electric-test'
    | '/workspaces/$workspaceId/vscode'
    | '/_app/_shell/routines_/$routineId'
    | '/_app/_shell/routines_/new'
    | '/_app/_shell/workspaces_/$workspaceId'
    | '/_app/hosts/$hostId/workspaces'
    | '/_app/hosts/$hostId/workspaces_/$workspaceId'
    | '/_app/projects/$projectId_/issues/$issueId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/_app/projects/$projectId_/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId'
    | '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId'
    | '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OnboardingSignInRoute: typeof OnboardingSignInRoute
  WorkspacesWorkspaceIdVscodeRoute: typeof WorkspacesWorkspaceIdVscodeRoute
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding_/sign-in': {
      id: '/onboarding_/sign-in'
      path: '/onboarding/sign-in'
      fullPath: '/onboarding/sign-in'
      preLoaderRoute: typeof OnboardingSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_shell': {
      id: '/_app/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppShellRouteImport
      parentRoute: typeof AppRoute
    }
    '/workspaces/$workspaceId/vscode': {
      id: '/workspaces/$workspaceId/vscode'
      path: '/workspaces/$workspaceId/vscode'
      fullPath: '/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof WorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces_/electric-test': {
      id: '/_app/workspaces_/electric-test'
      path: '/workspaces/electric-test'
      fullPath: '/workspaces/electric-test'
      preLoaderRoute: typeof AppWorkspacesElectricTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_shell/workspaces': {
      id: '/_app/_shell/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppShellWorkspacesRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/routines': {
      id: '/_app/_shell/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AppShellRoutinesRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/hosts/$hostId/workspaces': {
      id: '/_app/hosts/$hostId/workspaces'
      path: '/hosts/$hostId/workspaces'
      fullPath: '/hosts/$hostId/workspaces'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_shell/workspaces_/$workspaceId': {
      id: '/_app/_shell/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppShellWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/routines_/new': {
      id: '/_app/_shell/routines_/new'
      path: '/routines/new'
      fullPath: '/routines/new'
      preLoaderRoute: typeof AppShellRoutinesNewRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/routines_/$routineId': {
      id: '/_app/_shell/routines_/$routineId'
      path: '/routines/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof AppShellRoutinesRoutineIdRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/hosts/$hostId/workspaces/$workspaceId/vscode': {
      id: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      path: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId_/issues/$issueId': {
      id: '/_app/projects/$projectId_/issues/$issueId'
      path: '/projects/$projectId/issues/$issueId'
      fullPath: '/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts/$hostId/workspaces_/$workspaceId': {
      id: '/_app/hosts/$hostId/workspaces_/$workspaceId'
      path: '/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/workspaces/create/$draftId'
      path: '/projects/$projectId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId'
      path: '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId'
      path: '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId'
      path: '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId'
      path: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId'
      path: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppShellRouteChildren {
  AppShellRoutinesRoute: typeof AppShellRoutinesRoute
  AppShellWorkspacesRoute: typeof AppShellWorkspacesRoute
  AppShellRoutinesRoutineIdRoute: typeof AppShellRoutinesRoutineIdRoute
  AppShellRoutinesNewRoute: typeof AppShellRoutinesNewRoute
  AppShellWorkspacesWorkspaceIdRoute: typeof AppShellWorkspacesWorkspaceIdRoute
}

const AppShellRouteChildren: AppShellRouteChildren = {
  AppShellRoutinesRoute: AppShellRoutinesRoute,
  AppShellWorkspacesRoute: AppShellWorkspacesRoute,
  AppShellRoutinesRoutineIdRoute: AppShellRoutinesRoutineIdRoute,
  AppShellRoutinesNewRoute: AppShellRoutinesNewRoute,
  AppShellWorkspacesWorkspaceIdRoute: AppShellWorkspacesWorkspaceIdRoute,
}

const AppShellRouteWithChildren = AppShellRoute._addFileChildren(
  AppShellRouteChildren,
)

interface AppRouteChildren {
  AppShellRoute: typeof AppShellRouteWithChildren
  AppExportRoute: typeof AppExportRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppWorkspacesElectricTestRoute: typeof AppWorkspacesElectricTestRoute
  AppHostsHostIdWorkspacesRoute: typeof AppHostsHostIdWorkspacesRoute
  AppHostsHostIdWorkspacesWorkspaceIdRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  AppProjectsProjectIdIssuesIssueIdRoute: typeof AppProjectsProjectIdIssuesIssueIdRoute
  AppProjectsProjectIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute: typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppShellRoute: AppShellRouteWithChildren,
  AppExportRoute: AppExportRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppWorkspacesElectricTestRoute: AppWorkspacesElectricTestRoute,
  AppHostsHostIdWorkspacesRoute: AppHostsHostIdWorkspacesRoute,
  AppHostsHostIdWorkspacesWorkspaceIdRoute:
    AppHostsHostIdWorkspacesWorkspaceIdRoute,
  AppProjectsProjectIdIssuesIssueIdRoute:
    AppProjectsProjectIdIssuesIssueIdRoute,
  AppProjectsProjectIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute:
    AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute,
  AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute:
    AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute,
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OnboardingSignInRoute: OnboardingSignInRoute,
  WorkspacesWorkspaceIdVscodeRoute: WorkspacesWorkspaceIdVscodeRoute,
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute:
    HostsHostIdWorkspacesWorkspaceIdVscodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
